---
title: "SR4"
author: "petergraffy"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}


library(tidyverse)
library(dplyr)
library(ggplot2)
library(mapdata)
library(mapproj)
library(gridExtra)
library(viridis)
library(countrycode)
library(tableone)
library(kableExtra)

```


```{r}

here::set_here()

dir <- "/Users/saborpete/Desktop/Peter/Peter PhD/Dissertation/analysis/Dissertation/"

date <- Sys.Date()

# here we will create a folder to store the results

outdir <- paste0(dir, "Results",date)

#first check if the folder exists and if not then create it

if (file.exists(outdir)){
} else {
    dir.create(outdir)
}


```


# read in data

```{r}

dat <- read.csv("SR3rev.csv")

length(unique(dat$SOURCE))


length(unique(dat$PTDATA))

```


```{r}

dat$`Publication Date` <- ifelse(dat$PUBYEAR >= 1990 & dat$PUBYEAR < 1995, "1990-1995",
                      ifelse(dat$PUBYEAR >= 1995 & dat$PUBYEAR < 2000, "1995-2000",
                             ifelse(dat$PUBYEAR >= 2000 & dat$PUBYEAR < 2005, "2000-2005",
                                    ifelse(dat$PUBYEAR >= 2005 & dat$PUBYEAR < 2010, "2005-2010",
                                           ifelse(dat$PUBYEAR >= 2010 & dat$PUBYEAR < 2015, "2010-2015",
                                                  ifelse(dat$PUBYEAR >= 2015 & dat$PUBYEAR < 2020, "2015-2020",
                                                         ifelse(dat$PUBYEAR >= 2020 & dat$PUBYEAR < 2025, "2020-Present", NA)))))))


decade_label <- function(START) {
  END <- START + 9
  return(paste(START, END, sep = "-"))
}

dat$`Study Start` <- cut(dat$START, 
                   breaks = seq(1880, 2020, by = 10),
                   labels = sapply(seq(1880, 2010, by = 10), decade_label),
                   include.lowest = TRUE)


#write.csv(dat, "SR4.csv")

```


```{r}
table(dat$COUNTRY)

dat_filtered <- dat %>%
  group_by(COUNTRY) %>%
  filter(n() > 1)

table(dat_filtered$COUNTRY)

#write.csv(dat_filtered, "SRfiltered2.csv")
```


#### start here

```{r}
dat <- read.csv("SRfiltered2.csv")

```



# tile plot of countries most found in SR3


```{r}
dat$COUNTRY <- as.factor(dat$COUNTRY)
dat$DESIGN <- as.factor(dat$DESIGN)
dat$Meth <- as.factor(dat$Meth)

# # Define desired countries
# desired_countries <- c("Australia", "Brazil", "China", "Germany", "Greece", "Iran", "South Korea", "Switzerland", "USA", "Vietnam")
# 
# # Filter the dataset
# dat_filtered <- dat %>% 
#   filter(COUNTRY %in% desired_countries)

# Group by COUNTRY, DESIGN, and Meth, and count occurrences

method_counts <- dat %>%
  group_by(COUNTRY, DESIGN, Meth) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  slice(1)

# Now, create the heatmap with text labels
p1 <- ggplot(method_counts, aes(x = COUNTRY, y = DESIGN, fill = Meth, label = Count)) +
  geom_tile() +
  geom_text(color = "black", size = 3) + # Add text labels
  scale_fill_brewer(palette = "Set3") + # You can choose a different palette if needed
  labs(x = "Country", y = "Design", fill = "Method") +
  theme_minimal() + 
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),  # Remove panel border
        axis.line = element_line(color = "black")) # Remove axis lines
```


```{r}
png(
    filename = paste0(file.path(outdir, "tileplot_country_"), date, ".png"),
    width = 14,
    height = 10,
    units = "in",
    res = 500
  )


p1 <- ggplot(method_counts, aes(x = COUNTRY, y = DESIGN, fill = Meth, label = Count)) +
  geom_tile() +
  geom_text(color = "black", size = 3) + # Add text labels
  scale_fill_brewer(palette = "Set3") + # You can choose a different palette if needed
  labs(x = "Country", y = "Design", fill = "Method") +
  theme_minimal() + 
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),  # Remove panel border
        axis.line = element_line(color = "black")) # Remove axis lines

print(p1)
  
dev.off()

#ggsave("tileplotcountry.png", p1, width = 10, height = 7, dpi = 300)

```


```{r}

library(RColorBrewer)
display.brewer.pal(n = 8, name = 'Set3')
brewer.pal(n = 8, name = "Set3")

method_colors <- c("Conditional logistic regression" = "#8DD3C7",
                   "Cox Proportional Hazard" = "#FCCDE5",
                   "DLNM" = "#FFFFB3",
                   "GLM" = "#80B1D3",
                   "Logistic regression" = "#FDB462",
                   "Other" = "#B3DE69")

method_counts <- dat %>%
  group_by(PRIMARY, DESIGN, Meth) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  slice(1)

#method_counts<-read.csv("methodcounts.csv")

```


```{r}
png(
    filename = paste0(file.path(outdir, "tileplot_method_"), date, ".png"),
    width = 14,
    height = 10,
    units = "in",
    res = 500
  )

# Now, create the heatmap with text labels
p2 <- ggplot(method_counts, aes(x = PRIMARY, y = DESIGN, fill = Meth, label = Count)) +
  geom_tile() +
  geom_text(color = "black", size = 3) + # Add text labels
  scale_fill_manual(values = method_colors) +
  labs(x = "Outcome", y = "Design", fill = "Method") +
  theme_minimal() + 
  coord_flip() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),  # Remove panel border
        axis.line = element_line(color = "black")) # Remove axis lines

print(p2)
  
dev.off()

#ggsave("tileplotoutcome.png", p2, width = 10, height = 7, dpi = 300)


```



```{r}


table(dat$HEAT)

length(unique(dat$HEAT))

```


